# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "NdGameSdk"
version = "0.0.7"
languages = ["C", "CXX"]
cmake-after = """
add_compile_options(
    $<$<CONFIG:Debug>:/MDd>
    $<$<CONFIG:RelWithDebInfo>:/MD>
    $<$<CONFIG:RelWithDebInfo>:/Od>
    # noise 
    -Wno-unused-private-field
    -Wno-unused-variable
    -Wno-ignored-qualifiers
    -Wno-reorder-ctor
    -Wno-microsoft-unqualified-friend
)

set(SAFETYHOOK_FETCH_ZYDIS ON)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")

# Configure vcpkg
set(VCPKG_OVERLAY_TRIPLETS "${CMAKE_SOURCE_DIR}/vcpkg-overlays/triplets" CACHE STRING "" FORCE)
set(VCPKG_TARGET_TRIPLET   "x64-windows-ndgamesdk" CACHE STRING "" FORCE)

include(${CMAKE_SOURCE_DIR}/cmake/NdGameSdkInstall.cmake)
"""
 
[variables]
CMAKE_CONFIGURATION_TYPES = "Debug;RelWithDebInfo"
RUNTIME_OUTPUT_DIRECTORY = "${CMAKE_BINARY_DIR}/bin"
LIBRARY_OUTPUT_DIRECTORY = "${CMAKE_BINARY_DIR}/lib" 
PROJECT_TARGET = "FDG"

#https://github.com/gabime/spdlog 
[target.spdlog]
type = "static"
sources = ["dependencies/external/spdlog/src/*.cpp"]
include-directories = ["dependencies/external/spdlog/include"]
compile-definitions = ["SPDLOG_COMPILED_LIB", "SPDLOG_WCHAR_TO_UTF8_SUPPORT", "SPDLOG_FMT_EXTERNAL", "SPDLOG_FMT_EXTERNAL_HO"]
link-libraries = ["fmt::fmt-header-only"]
alias = "spdlog::spdlog"
 
#https://github.com/g-truc/glm
[target.glm_static]
type = "static" 
sources = ["dependencies/external/glm/glm/**.cpp"]  
include-directories = ["dependencies/external/glm"] 
alias = "glm::glm"

[fetch-content.simpleini]
git = "https://github.com/brofield/simpleini"
tag = "09c21bda1dc1b578fa55f4a005d79b0afd481296"

[fetch-content.safetyhook]
git = "https://github.com/cursey/safetyhook"
tag = "629558c64009a7291ba6ed5cfb49187086a27a47"

[vcpkg]
version = "74e6536"
url = "https://github.com/microsoft/vcpkg/archive/74e6536215718009aae747d86d84b78376bf9e09.tar.gz"
packages = ["boost-thread", "boost-signals2", "boost-container", "dstorage", "lz4", "zlib", "nlohmann-json", "fmt"]

[find-package.Boost]
version = "1.85.0"
required = true 
config = false
components = ["thread", "signals2"]
 
[find-package.dstorage]
required = true
config = true

[find-package.nlohmann_json]
required = true
config = true

[find-package.lz4]
required = true
config = true

[find-package.zlib]
required = true

[find-package.fmt]
required = true
config = true

[template.NdGameSdk]
type = "shared"
sources = [
"src/NdGameSdk/*.cpp",
"src/NdGameSdk/components/**.cpp",
"src/NdGameSdk/shared/**.cpp",
"src/NdGameSdk/shared/**.c",
"src/NdGameSdk/database/**.cpp",
"src/NdGameSdk/sidbase/**.cpp"
] 
headers = [
"src/NdGameSdk/*.hpp",
"src/NdGameSdk/config/**.hpp",
"src/NdGameSdk/components/**.hpp",
"src/NdGameSdk/shared/**.hpp",
"src/NdGameSdk/shared/**.h",
"src/NdGameSdk/database/**.hpp",
"src/NdGameSdk/sidbase/**.hpp"
]
include-directories = ["src", "./shared", "dependencies/external/glm", "dependencies/external/spdlog/include"]
compile-features = ["cxx_std_23"]
alias = "FDG::NdGameSdk"
link-libraries = [
    "nlohmann_json::nlohmann_json"
]
private-link-libraries = [
    "spdlog::spdlog",
    "glm_static",
    "Utility",
    "Boost::thread",
    "Boost::signals2",
    "Boost::container",
    "lz4::lz4",
    "ZLIB::ZLIB"
]
cmake-before="""
"""
cmake-after = """
set_property(GLOBAL APPEND PROPERTY NDGAMESDK_SDK_TARGETS ${CMKR_TARGET})
"""
  
[template.NdGameSdk.properties]
OUTPUT_NAME = "NdGameSdk"
RUNTIME_OUTPUT_DIRECTORY = "${RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
LIBRARY_OUTPUT_DIRECTORY = "${LIBRARY_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY = "${LIBRARY_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
#PUBLIC_HEADER = "TODO"

[template.Runtime.properties]
OUTPUT_NAME = "${PROJECT_TARGET}.Runtime"
SUFFIX = ".asi"
RUNTIME_OUTPUT_DIRECTORY = "${RUNTIME_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
LIBRARY_OUTPUT_DIRECTORY = "${LIBRARY_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
ARCHIVE_OUTPUT_DIRECTORY = "${LIBRARY_OUTPUT_DIRECTORY}/${PROJECT_TARGET}"
CXX_MODULE_STD = true
  
[template.Runtime]
type = "shared"  
sources = ["src/Runtime/**.cpp", "src/Runtime/**.c"] 
headers = ["src/Runtime/**.hpp", "src/Runtime/**.h"]
compile-features = ["cxx_std_23"]
include-directories = ["shared/", "src/Runtime/"]
compile-definitions = [ "${CMKR_TARGET}", "ND_GAME_NAME=\"${CMKR_TARGET}\"", "ND_RuntimeClient_EXPORTS", "ND_RuntimeClient_VERSION=\"${PROJECT_VERSION}\""]
link-libraries = [
    "${CMKR_TARGET}SDK",
    "Utility",
    "spdlog::spdlog"
]
private-link-libraries = [
	"Boost::thread",
	"Boost::signals2",
    "SimpleIni"
] 
# causes an issue with not compiling CMKR TARGET after 0.2.17:
# https://github.com/build-cpp/cmkr/blob/45e346b4a3cc10619fd8b5c0c6e773f3c6f04a7b/src/cmake_generator.cpp#L1328
cmake-before="""
"""

[target.Utility]
type = "static"
sources = ["shared/**.cpp", "shared/**.c"]
headers = ["shared/**.hpp", "shared/**.h"]
compile-features = ["cxx_std_23"]
compile-options = ["/MP"]
compile-definitions = ["PROJECT_NAME=\"${PROJECT_TARGET}.Runtime\""] 
alias = "Utility::Utility"
private-link-libraries = ["Boost::signals2"]
link-libraries = [
    "spdlog::spdlog",
    "safetyhook"
] 
    
[target.T1XSDK]  
type = "NdGameSdk"
compile-definitions = ["T1X", "ND_GAME_NAME=\"${PROJECT_TARGET}\""]
sources = [
"src/NdGameSdk/ndgame/t1x/**.cpp",
"src/NdGameSdk/ndgame/t1x/**.c"
] 
headers = [
"src/NdGameSdk/ndgame/t1x/**.hpp", 
"src/NdGameSdk/ndgame/t1x/**.h",
"src/NdGameSdk/regenny/t1x/**.hpp",
"src/NdGameSdk/regenny/t1x/**.h"
] 
cmake-before="""
set(PROJECT_TARGET "T1X")
"""

[target.T1X]
type = "Runtime"

[target.T2RSDK]  
type = "NdGameSdk"
compile-definitions = ["T2R", "ND_GAME_NAME=\"${PROJECT_TARGET}\""]
sources = [
"src/NdGameSdk/ndgame/t2r/**.cpp",
"src/NdGameSdk/ndgame/t2r/**.c"
] 
headers = [
"src/NdGameSdk/ndgame/t2r/**.hpp", 
"src/NdGameSdk/ndgame/t2r/**.h",
"src/NdGameSdk/regenny/t2r/**.hpp",
"src/NdGameSdk/regenny/t2r/**.h"
] 
cmake-before="""
set(PROJECT_TARGET "T2R")
"""

[target.T2R]
type = "Runtime"
