name: Build NdGameSdk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      zip: ${{ github.workspace }}/bin.7z
      zip_pdb: ${{ github.workspace }}/bin_pdb.7z
    permissions:
      contents: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ github.repository_id }}-${{ runner.os }}-${{ runner.arch }}-dep
      - name: Configure cmkr
        run: cmake -P cmkr.cmake
      - name: Configure project
        run: cmake --preset vs2022
      - name: Build
        run: cmake --build build --parallel --config RelWithDebInfo
      - name: Pack binary
        working-directory: build
        run: |
          7z a -mx9 -mtm- ${{ env.zip_pdb }} bin
          Remove-Item -Path bin -Recurse -Include *.lib,*.pdb
          7z a -mx9 -mtm- ${{ env.zip }} bin
      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $cmdOutput = Split-Path -Path $pwd -Leaf
          $branch = "${{ github.ref_name }}"
          $branch = $branch.replace('/','-')
          $_ver = "0.0.$(git rev-list HEAD --count)-$(git rev-parse --short=8 HEAD)+${{ github.run_number }}-branch-$branch"
          $zip_name="$cmdOutput-$_ver"
          cp "${{ env.zip }}" "$zip_name.7z"
          cp "${{ env.zip_pdb }}" "$zip_name-pdb.7z"
          
          gh release create "$_ver" `
          "$zip_name.7z" `
          "$zip_name-pdb.7z" `
          --target ${{ GITHUB.SHA }} -t "$_ver" --prerelease
