name: CMake

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure cmkr
        run: cmake -P cmkr.cmake
      - name: Configure project
        run: cmake --preset vs2022
      - name: Build
        run: cmake --build build --parallel --config RelWithDebInfo
      - name: Install
        run: cmake --install build  --config RelWithDebInfo

